# -*- coding: utf-8 -*-
"""econ 490

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b1igtkQVrOmWoqbi13sxaoCDilO6lDdu
"""

pip install kmodes
#I added matrix.cvs to google doc: erases after log-off
# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/gdrive')
# %cd /gdrive

import numpy as np
from kmodes import kmodes

# random categorical data
data = np.random.choice(20, (100, 10))

km = kmodes.KModes(n_clusters=4, init='Huang', n_init=5, verbose=1)

clusters = km.fit_predict(data)

# Print the cluster centroids
print(km.cluster_centroids_)

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 13, cost: 805.0
Run 1, iteration: 2/100, moves: 2, cost: 805.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 21, cost: 804.0
Run 2, iteration: 2/100, moves: 7, cost: 797.0
Run 2, iteration: 3/100, moves: 5, cost: 796.0
Run 2, iteration: 4/100, moves: 0, cost: 796.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 17, cost: 808.0
Run 3, iteration: 2/100, moves: 1, cost: 808.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 26, cost: 801.0
Run 4, iteration: 2/100, moves: 6, cost: 798.0
Run 4, iteration: 3/100, moves: 1, cost: 798.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 25, cost: 809.0
Run 5, iteration: 2/100, moves: 4, cost: 807.0
Run 5, iteration: 3/100, moves: 0, cost: 807.0
Best run was number 2
[[ 3  6  3  6  6 15 19  7  1  8]
 [ 9  0  8  2 12 13 17  1 15  7]
 [13  1 12  3  4  1  2 11 16  0]
 [ 2 19  7 15 17  0  0 15 17  5]]
